version: '2'
services:
    amethystps-app:
        image: amethystps
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://amethystps-postgresql:5432/amethystps
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    amethystps-postgresql:
        extends:
            file: postgresql.yml
            service: amethystps-postgresql
